'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-AGFTUAJ;Initial Catalog=BON;Integrated Security=True")>  _
        Public ReadOnly Property BONConnectionString() As String
            Get
                Return CType(Me("BONConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2016")>  _
        Public Property fltbonjr() As Integer
            Get
                Return CType(Me("fltbonjr"),Integer)
            End Get
            Set
                Me("fltbonjr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fltbontbw() As Integer
            Get
                Return CType(Me("fltbontbw"),Integer)
            End Get
            Set
                Me("fltbontbw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BONConnectionStringUserOverride() As String
            Get
                Return CType(Me("BONConnectionStringUserOverride"),String)
            End Get
            Set
                Me("BONConnectionStringUserOverride") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13893118")>  _
        Public Property GRIDrowseven() As String
            Get
                Return CType(Me("GRIDrowseven"),String)
            End Get
            Set
                Me("GRIDrowseven") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1048575")>  _
        Public Property GRIDrowsodd() As String
            Get
                Return CType(Me("GRIDrowsodd"),String)
            End Get
            Set
                Me("GRIDrowsodd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property GRIDforecoloreven() As String
            Get
                Return CType(Me("GRIDforecoloreven"),String)
            End Get
            Set
                Me("GRIDforecoloreven") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property GRIDforecolorodd() As String
            Get
                Return CType(Me("GRIDforecolorodd"),String)
            End Get
            Set
                Me("GRIDforecolorodd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16777215")>  _
        Public Property DISPtextboxbackcolor() As String
            Get
                Return CType(Me("DISPtextboxbackcolor"),String)
            End Get
            Set
                Me("DISPtextboxbackcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLogon() As String
            Get
                Return CType(Me("UserLogon"),String)
            End Get
            Set
                Me("UserLogon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property DISPtextboxerror() As String
            Get
                Return CType(Me("DISPtextboxerror"),String)
            End Get
            Set
                Me("DISPtextboxerror") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7642362")>  _
        Public Property GRIDcellnotused() As String
            Get
                Return CType(Me("GRIDcellnotused"),String)
            End Get
            Set
                Me("GRIDcellnotused") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property STOCKupdateclosed() As Boolean
            Get
                Return CType(Me("STOCKupdateclosed"),Boolean)
            End Get
            Set
                Me("STOCKupdateclosed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Inventaris 2016")>  _
        Public Property STOCKstandaardtrans() As String
            Get
                Return CType(Me("STOCKstandaardtrans"),String)
            End Get
            Set
                Me("STOCKstandaardtrans") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fltbondel() As Integer
            Get
                Return CType(Me("fltbondel"),Integer)
            End Get
            Set
                Me("fltbondel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fltbonvs() As Integer
            Get
                Return CType(Me("fltbonvs"),Integer)
            End Get
            Set
                Me("fltbonvs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fltbongst() As Integer
            Get
                Return CType(Me("fltbongst"),Integer)
            End Get
            Set
                Me("fltbongst") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fltbonuv() As Integer
            Get
                Return CType(Me("fltbonuv"),Integer)
            End Get
            Set
                Me("fltbonuv") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fltbonfnr() As Integer
            Get
                Return CType(Me("fltbonfnr"),Integer)
            End Get
            Set
                Me("fltbonfnr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fltboncnr() As Integer
            Get
                Return CType(Me("fltboncnr"),Integer)
            End Get
            Set
                Me("fltboncnr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property FirstFNR() As Integer
            Get
                Return CType(Me("FirstFNR"),Integer)
            End Get
            Set
                Me("FirstFNR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16711680")>  _
        Public Property GRIDselectfg() As String
            Get
                Return CType(Me("GRIDselectfg"),String)
            End Get
            Set
                Me("GRIDselectfg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16757759")>  _
        Public Property GRIDselectbg() As String
            Get
                Return CType(Me("GRIDselectbg"),String)
            End Get
            Set
                Me("GRIDselectbg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("65280")>  _
        Public Property GRIDcellgratis() As String
            Get
                Return CType(Me("GRIDcellgratis"),String)
            End Get
            Set
                Me("GRIDcellgratis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16022884")>  _
        Public Property GRIDcellmemo() As String
            Get
                Return CType(Me("GRIDcellmemo"),String)
            End Get
            Set
                Me("GRIDcellmemo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property fltfilterdatum() As Boolean
            Get
                Return CType(Me("fltfilterdatum"),Boolean)
            End Get
            Set
                Me("fltfilterdatum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property fltfilterleegBON() As Boolean
            Get
                Return CType(Me("fltfilterleegBON"),Boolean)
            End Get
            Set
                Me("fltfilterleegBON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2019")>  _
        Public Property JaarCopy() As Integer
            Get
                Return CType(Me("JaarCopy"),Integer)
            End Get
            Set
                Me("JaarCopy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property XCode() As Integer
            Get
                Return CType(Me("XCode"),Integer)
            End Get
            Set
                Me("XCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fltbonpart() As Integer
            Get
                Return CType(Me("fltbonpart"),Integer)
            End Get
            Set
                Me("fltbonpart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TotalsAllowed() As String
            Get
                Return CType(Me("TotalsAllowed"),String)
            End Get
            Set
                Me("TotalsAllowed") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Bon2017.My.MySettings
            Get
                Return Global.Bon2017.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
